### PR TITLE
Refactor & add tests

### PR DESCRIPTION
**Pull request by dongilbert**
Thanks for this great package! I'm getting started with i18next in my Laravel app with a react frontend, and this was just what I needed. I wanted to contribute back so refactored it a bit and added unit tests. The tests can be fleshed out a bit more (need to write tests for flattening), but I'm happy with where it's at at the moment and wanted to create the PR sooner rather than later.

Let me know if there's any additional changes you'd like me to make!

### CODE REVIEW

**Comment by tdondich** [comment]
Huge.  Thank you for the contribution!  Will review today and look to merge!

**Comment by dongilbert** [comment]
Great :) I'm adding a couple more config options as well as the flatten tests. I'll ping here when it's ready.

**Comment by dongilbert** [comment]
Ok - just pushed.

**Review by tdondich — APPROVED** [review]

**Comment by tdondich** [comment]
@dongilbert Thanks a lot.  Tomorrow, I'll be moving this project to our @processmaker account and registering it with packagist.  I'll be sharing your commit around to show the excitement.  Let's talk more about how to build more cool stuff together!

**Comment by dongilbert** [comment]
Awesome, thanks!

**Comment by tdondich** [comment]
@dongilbert  Please note, the repository has moved to the ProcessMaker github account.  We'll be publishing to packagist shortly.

**Pull request merged**
